### ISSUE TITLE
Why did you follow me?

### ISSUE THREAD

**Issue by Sharan-Python** [PremKumarMishra/Python-Tkinter-Desginer#2]
It looks like you want me to do something for your designer.... Do you want me to validate it? Test it and give feedback? Anything else...

By the way my repositories are created for friends ETC, I am not a serious programmer I just code for fun.

**Comment by PremKumarMishra** [comment]
I followed you to work in my Desinger.Sorry i was out of home could not response your messages.

**Comment by Sharan-Python** [comment]
Im sorry I have my own projects going on so I cannot participate right now. I will comment when I am done with my projects

**Comment by Sharan-Python** [comment]
If you want to invite someone to your repository you should go to you repository settings > Manage access > Invite a collaborator

**Comment by PremKumarMishra** [comment]
oh k No problem
